#pragma once
#include <windows.h>

/* Kernel32 API imports */
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI KERNEL32$CreateProcessA(
    LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES,
    BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
DECLSPEC_IMPORT WINBASEAPI VOID WINAPI KERNEL32$Sleep(DWORD);
DECLSPEC_IMPORT WINBASEAPI DWORD WINAPI KERNEL32$GetLastError(VOID);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI KERNEL32$CloseHandle(HANDLE);

/* User32 API imports */
DECLSPEC_IMPORT WINBASEAPI INT WINAPI USER32$GetWindowTextA(HWND, LPSTR, INT);
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI USER32$IsWindowVisible(HWND);
DECLSPEC_IMPORT WINUSERAPI HWND WINAPI USER32$GetTopWindow(HWND);
DECLSPEC_IMPORT WINUSERAPI HWND WINAPI USER32$GetWindow(HWND, UINT);

/* WinHTTP API imports */
DECLSPEC_IMPORT WINHTTPAPI HINTERNET WINAPI WINHTTP$WinHttpOpen(
    LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD);
DECLSPEC_IMPORT WINHTTPAPI HINTERNET WINAPI WINHTTP$WinHttpConnect(
    HINTERNET, LPCWSTR, INTERNET_PORT, DWORD);
DECLSPEC_IMPORT WINHTTPAPI HINTERNET WINAPI WINHTTP$WinHttpOpenRequest(
    HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR*, DWORD);
DECLSPEC_IMPORT WINHTTPAPI BOOL WINAPI WINHTTP$WinHttpAddRequestHeaders(
    HINTERNET, LPCWSTR, DWORD, DWORD);
DECLSPEC_IMPORT WINHTTPAPI BOOL WINAPI WINHTTP$WinHttpSendRequest(
    HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD, DWORD, DWORD_PTR);
DECLSPEC_IMPORT WINHTTPAPI BOOL WINAPI WINHTTP$WinHttpReceiveResponse(
    HINTERNET, LPVOID);
DECLSPEC_IMPORT WINHTTPAPI BOOL WINAPI WINHTTP$WinHttpReadData(
    HINTERNET, LPVOID, DWORD, LPDWORD);
DECLSPEC_IMPORT WINHTTPAPI BOOL WINAPI WINHTTP$WinHttpCloseHandle(HINTERNET);

/* MSVCRT function mappings */
#define strstr      MSVCRT$strstr
#define strlen      MSVCRT$strlen
#define memset      MSVCRT$memset
#define _snprintf   MSVCRT$_snprintf
#define strncpy_s   MSVCRT$strncpy_s

/* MSVCRT imports */
DECLSPEC_IMPORT char * __cdecl MSVCRT$strstr(const char *, const char *);
DECLSPEC_IMPORT size_t __cdecl MSVCRT$strlen(const char *);
DECLSPEC_IMPORT void * __cdecl MSVCRT$memset(void *, int, size_t);
DECLSPEC_IMPORT int __cdecl MSVCRT$_snprintf(LPSTR, size_t, LPCSTR, ...);
DECLSPEC_IMPORT errno_t __cdecl MSVCRT$strncpy_s(LPSTR, size_t, LPCSTR, size_t);
